<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saqibs-MacBook-Pro.local" name="TestBoALocationsPage" tests="18" failures="0" timestamp="28 Mar 2019 08:07:33 GMT" time="134.194" errors="1">
  <testcase name="testLocationsTitle" time="4.384" classname="TestBoALocationsPage"/>
  <testcase name="testAstoriaLink" time="9.844" classname="TestBoALocationsPage"/>
  <testcase name="testBankAtmLogo" time="6.004" classname="TestBoALocationsPage"/>
  <testcase name="testClickNY" time="8.108" classname="TestBoALocationsPage"/>
  <testcase name="testSearchInput" time="6.576" classname="TestBoALocationsPage"/>
  <testcase name="testClearFilter" time="13.445" classname="TestBoALocationsPage"/>
  <testcase name="testDoneFilter" time="14.641" classname="TestBoALocationsPage"/>
  <testcase name="testFilterSearch" time="4.563" classname="TestBoALocationsPage"/>
  <testcase name="testFilterClicks" time="10.621" classname="TestBoALocationsPage"/>
  <testcase name="testInternationLink" time="7.076" classname="TestBoALocationsPage">
    <error type="java.lang.AssertionError" message="expected [https://locators.bankofamerica.com/international.html&amp;check_list=4397] but found [https://locators.bankofamerica.com/international.html]">
      <![CDATA[java.lang.AssertionError: expected [https://locators.bankofamerica.com/international.html&check_list=4397] but found [https://locators.bankofamerica.com/international.html]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at BoALocationsPage.internationalAtms(BoALocationsPage.java:181)
	at TestBoALocationsPage.testInternationLink(TestBoALocationsPage.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </error>
  </testcase> <!-- testInternationLink -->
  <testcase name="testFilterMessage" time="7.123" classname="TestBoALocationsPage"/>
  <testcase name="testMapZoomIn" time="7.127" classname="TestBoALocationsPage"/>
  <testcase name="testLocationsPlaceHolder" time="4.246" classname="TestBoALocationsPage"/>
  <testcase name="testMapExitFullScreen" time="7.060" classname="TestBoALocationsPage"/>
  <testcase name="testLocationsUrl" time="4.418" classname="TestBoALocationsPage"/>
  <testcase name="testSearchBtnHolder" time="4.420" classname="TestBoALocationsPage"/>
  <testcase name="testMapFullScreen" time="7.755" classname="TestBoALocationsPage"/>
  <testcase name="testMapZoomOut" time="6.783" classname="TestBoALocationsPage"/>
</testsuite> <!-- TestBoALocationsPage -->
